name: Java Spring Boot CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Purge OWASP DC cached data (prevent stale local data)
        run: |
          rm -rf ~/.m2/repository/org/owasp/dependency-check-data || true

      - name: OWASP Dependency-Check (with NVD API key)
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
        run: |
          # (Güvenli doğrulama) Key uzunluğu gelsin diye sadece karakter sayisini yazdiriyoruz
          echo "NVD_API_KEY length: ${#NVD_API_KEY}"

          mvn -Pprod -DskipTests \
              -DnvdApiKey="${NVD_API_KEY}" \
              -Danalyzer.knownExploitedVulnerabilities.enabled=false \
              org.owasp:dependency-check-maven:check
        continue-on-error: true

      # Rapor oluştuysa yükle (yoksa sessizce atla)
      - name: Upload OWASP Dependency Check Reports
        if: ${{ hashFiles('**/target/dependency-check-report.json') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-reports
          path: |
            **/target/dependency-check-report.json

      - name: SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: >
          mvn -Pprod -DskipTests verify sonar:sonar
          -Dsonar.projectKey=simayaydin_etiya-project
          -Dsonar.organization=simayaydin
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      - name: Upload build artifact (.jar)
        uses: actions/upload-artifact@v4
        with:
          name: spring-boot-app
          path: target/*.jar
