name: Java Spring Boot CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven (no tests)
      run: mvn clean verify -DskipTests

    - name: OWASP Dependency Check
      run: mvn org.owasp:dependency-check-maven:check -X

    - name: Upload OWASP Dependency Check Reports
      uses: actions/upload-artifact@v4
      with:
        name: dependency-check-reports
        path: |
          target/dependency-check-report.json

    # SONAR ANALYSIS 
    - name: SonarCloud Scan
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: >
        mvn verify sonar:sonar
        -Dsonar.projectKey=simayaydin_etiya-project
        -Dsonar.organization=simayaydin
        -Dsonar.host.url=https://sonarcloud.io
        -Dsonar.login=${{ secrets.SONAR_TOKEN }}

    - name: Upload build artifact (.jar)
      uses: actions/upload-artifact@v4
      with:
        name: spring-boot-app
        path: target/*.jar
